### PR TITLE
Remove SIGINFO stack tracing on Ctrl-T

### LINKED ISSUE #575: Fix stacktrace after pressing crtl-T during shopify serve
# Issue summary
In https://github.com/Shopify/shopify-app-cli/issues/570 this trace confused a developer for a problem with their app. This, however, should not happen at all and should be suppressed.

## Steps to reproduce the problem

1. `shopify serve` in a project
1. `ctrl-t` after the server is running
1. stacktrace

The stacktrace looks like this:
<details>

```
SIGINFO:
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `select'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `block in system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `loop'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/context.rb:228:in `system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/project_types/node/commands/serve.rb:32:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/project_types/node/commands/serve.rb:29:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/monorail.rb:25:in `log'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/bin/shopify:37:in `block in <main>'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/bin/shopify:36:in `<main>'
```

</details>

### PR DESCRIPTION
**Pull request by paulomarg**
### WHY are these changes introduced?

Fixes #575 

The default SIGINFO handling was to print out a stack trace, which doesn't really do anything except print out a jarring number of lines, before proceeding with the actual action we want.

### WHAT is this pull request doing?

Unsetting the default SIGINFO handler by setting an empty one before registering our own (which opens the App).

### CODE REVIEW

File: lib/project_types/rails/commands/serve.rb [hunk 1]
```diff
@@ -22,6 +22,9 @@ def call(*)
         )
         if @ctx.mac? && project.env.shop
           @ctx.puts("{{*}} Press {{yellow: Control-T}} to open this project in {{green:#{project.env.shop}}} ")
+
+          # Reset any previous SIGINFO handling we had so the only action we take is opening the URL
+          trap('INFO', 'DEFAULT')
```
Comment (tanema) [inline lib/project_types/rails/commands/serve.rb:27]: Should this be done in the context method rather than repeated across commands?

Comment (paulomarg) [reply lib/project_types/rails/commands/serve.rb]: It should. I checked and this method isn't used anywhere else, so the repetition is pointless. Fixed in 0fa73e2.
