### PR TITLE
fixes logic in prompt for updating application url

### LINKED ISSUE #422: The CLI tool does not prompt user to update the app url each time a new ngrok tunnel is started
# Issue summary

Each time a new ngrok tunnel is started, the cli tool does not prompt me to update the app url. 

## Expected behavior

What do you think should happen?

The tool should prompt me to update the new app url

## Actual behavior

What actually happens?

There is no prompt.
The whitelisted urls are updated though app url is not in the partners dashboard.
As of now, I have to manually go to the partners dashboard and update it.

Screen Shot 2019-12-13 at 9 25 44 AM

## Steps to reproduce the problem

1. each time a tunnel gets expired, I start a new one using 'shopify tunnel stop' and 'shopify tunnel start'
1. start the server in 'shopify serve'
1. Update the app url in the partners dashboard

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Shopify App CLI
- Operating System: macOS 10.14.6 (18G103)
- Shell: GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18

### PR DESCRIPTION
**Pull request by katiedavis**
### WHY are these changes introduced?

Fixes #422  

### WHAT is this pull request doing?

We should just prompt if we have a new application url instead of only prompting if it's not a ngrok url. This also fixes an issue with the callback url being written twice.

### CODE REVIEW

File: lib/shopify-cli/tasks/update_dashboard_urls.rb [hunk 1]
```diff
@@ -22,21 +22,21 @@ def call(ctx, url:)
       end
 
       def check_application_url(application_url, new_url)
-        return false if application_url.match(NGROK_REGEX) && new_url.match(NGROK_REGEX)
+        return false if application_url.match(new_url)
```
Comment (tylerball) [inline lib/shopify-cli/tasks/update_dashboard_urls.rb]: can we remove the NGROK_REGEX var too?

Comment (katiedavis) [reply lib/shopify-cli/tasks/update_dashboard_urls.rb]: Nope we still use when we write urls!

Comment (tylerball) [reply lib/shopify-cli/tasks/update_dashboard_urls.rb]: Right!
