### PR TITLE
Remove Ctrl-T from serve and always print URLs

### LINKED ISSUE #769: Ctrl-T to open store doesn't work
Per feedback in #762 

> Control-T to open store doesn't work
> ```
> ✓ Whitelist URLS updated in Partners Dashboard
> ⭑ Press  Control-T to open this project
> load: 0.88  cmd: fsevent_watch 14939 waiting 0.01u 0.04s
> ┃ Thread TID-owsn0ym2k
> ┃ Thread: TID-owsn0ym2k
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:334:in `backtrace'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:334:in `block in log_thread_status'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:327:in `each'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:327:in `log_thread_status'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:460:in `block in setup_signals'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:117:in `join'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:117:in `run'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/rack/handler/puma.rb:73:in `run'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:39:in `start'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
> ┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
> ┃ bin/rails:4:in `<main>'
> ┃ Thread TID-owsn1e12k
> ┃ Thread: TID-owsn1e12k
> Please open this URL in your browser:
> https://....
> ```

### PR DESCRIPTION
**Pull request by paulomarg**
### WHY are these changes introduced?

Fixes #769 

Currently, the `serve` command only prints out the login URL for the app when the developer presses `Ctrl-T`. However, that approach has two main flaws:
* Not all OSs support Ctrl-T (SIGINFO)
* In the case of rails, the URL is printed along with the stack trace for all of the Puma threads, which makes it very hard to find

### WHAT is this pull request doing?

In order to make it easier for the developer to find the login URL (aside from running `open` in a different window), this PR prints out the URL prior to starting the server. Since that doesn't depend on any signals, it also does this on any OS.

CC @attaboy @gfscott 

Before:
before

After:
after

### CODE REVIEW

File: lib/project_types/node/messages/messages.rb [hunk 1]
```diff
@@ -202,7 +202,10 @@ module Messages
             host_must_be_https: "HOST must be a HTTPS url.",
           },
 
-          open_info: "{{*}} Press {{yellow: Control-T}} to open this project in {{green:%s}} ",
+          open_info: <<~MESSAGE,
+            {{*}} To view your app, open the following URL in your browser:
+            {{green:%s}}
+          MESSAGE
```
Comment (mkevinosullivan) [inline lib/project_types/node/messages/messages.rb:208]: Why not add the newlines (blank lines) before and after the `open_info` message in the `messages.rb` file and remove the `"\n"` from the `ctx.puts` in the `serve.rb` files?

**Review by gfscott — APPROVED** [review]

File: lib/project_types/node/messages/messages.rb (hunk 1 above)
Comment (paulomarg) [reply lib/project_types/node/messages/messages.rb:208]: That's a great question, and that's the way I implemented it at first. But then I started thinking if those `\n`s are part of the message or of the layout I'm going for in the CLI.

Comment (paulomarg) [reply lib/project_types/node/messages/messages.rb:208]: Also, this one is more for @gfscott: we already have a 'generic' way of printing out a URL, which says `Please open this URL in your browser: ...`. I was also torn if it would be better to use that here and keep it consistent or if this scenario called for a little more context.

**Review by mkevinosullivan — APPROVED** [review]

File: lib/project_types/node/messages/messages.rb (hunk 1 above)
Comment (gfscott) [reply lib/project_types/node/messages/messages.rb:208]: I think the additional context is valuable in this case! It's not just opening a URL, it's a required step to complete the OAuth flow. 

We could even up the detail level and make it a little more conversational:
```
{{*}} To install and start using your app, open this URL in your browser:
```
