### PR TITLE
check webhook topic against array and fix file location

### LINKED ISSUE #424: generate webhook navigation, information & missing validation
# Issue summary
`shopify generate webhook` surprised me in a few ways:

1. First of all I thought I could navigate the big list by typing the number (I want to generate all the product webhooks and they are 50, 51, 52), so I typed 5 and was ready to type 0 but 5 was taken as a selection already (I was expecting to enter the selection with e) => it generated for CHECKOUTS_CREATE
2. It says that the webhook is “generated in config/webhooks” but in reality it’s in `shopify_app.rb` under `config.webhooks`
3. It doesn’t validate the input, hence I mistyped PRODUCTS_UPDATEE and I got 
```
$ shopify generate webhook PRODUCTS_UPDATEE
✓ PRODUCTS_UPDATEE generated in config/webhooks
```
with code:
```
  config.webhooks = [
    {topic: 'products/updatee', address: 'https://b1ce1070.ngrok.io/webhooks/products/updatee', format: 'json'},
```

## Expected behavior

Respectively:
1. Either disable navigation by typing numbers or wait to get `e` to get the selection
2. The msg should explain that the topic is in `shopify_app.rb` under `config.webhooks`
3. Input should be validated

## Specifications

- App type: rails
- Operating System: MacOS Mojave 10.14.6
- Shell: GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin16.3.0)
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

### PR DESCRIPTION
**Pull request by katiedavis**
fixes #424 
This is pretty basic but guards against typing a fake webhook topic.

### CODE REVIEW

File: lib/shopify-cli/app_types/rails.rb [hunk 1]
```diff
@@ -31,7 +31,7 @@ def open_url
         end
 
         def webhook_location
-          "config/webhooks"
+          "shopify_app.rb"
```
Comment (tanema) [inline lib/shopify-cli/app_types/rails.rb]: What is this doing? Is this the initializer? Should it be config/initializers/shopify_app.rb?

Comment (katiedavis) [reply lib/shopify-cli/app_types/rails.rb]: Yes, I'll put the full path. This is just where shopify_app generates the code.
