### PR TITLE
Fix handling of project name when called from inside subdirectory

### LINKED ISSUE #591: Extract out `Project.project_name` method
As suggested by @mkevinosullivan in https://github.com/Shopify/shopify-app-cli/pull/565#discussion_r422334899

### PR DESCRIPTION
**Pull request by andyw8**
### WHY are these changes introduced?

Fixes #591 and #598

### WHAT is this pull request doing?

* Extracts out the `project_name` method.
* Changes the behaviour so that the correct project name is shown, even if run from within a nested directory.

### CODE REVIEW

File: lib/shopify-cli/project.rb [hunk 1]
```diff
@@ -80,6 +80,10 @@ def write(ctx, app_type, identifiers = {})
         ctx.write('.shopify-cli.yml', YAML.dump(content))
       end
 
+      def project_name
```
Comment (tanema) [inline lib/shopify-cli/project.rb:83]: Should this be `project_name`? It feels weird to me to have Project.project_name. project project. Although I guess Project.name would be too generic. 🤷

Comment (andyw8) [reply lib/shopify-cli/project.rb:83]: We also have `current_project_type` which could be renamed to `current_type`.
