### PR TITLE
Conditional partners url

### LINKED ISSUE #880: Improve support for working a local partners app
# Issue summary

We currently have `partners.shopify.com` hardcoded in several messages, which results in incorrect links when running a development version of the partners app locally.

I'm considering extracting this out, and then changing the behaviour to use the correct hostname.

Any thoughts/concerns? @tanema @paulomarg @mkevinosullivan 

cc @mllemango

### PR DESCRIPTION
**Pull request by mllemango**
### WHY are these changes introduced?

Fixes #880 

### WHAT is this pull request doing?
image

Partners URL no longer hardcoded, introduces extra function to detect if user is using local partners and use the appropriate link.

### CODE REVIEW

File: lib/project_types/node/commands/create.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@
 module Node
   module Commands
     class Create < ShopifyCli::SubCommand
+      LOCAL_DEBUG = 'SHOPIFY_APP_CLI_LOCAL_PARTNERS'
```
Comment (andyw8) [inline lib/project_types/node/commands/create.rb:5]: Rather than re-declaring this constant, we can reference the existing one, e.g. `ShopifyCli::PartnersApi::LOCAL_DEBUG` ?

File: lib/project_types/node/commands/create.rb [hunk 2]
```diff
@@ -112,6 +113,11 @@ def build(name)
           @ctx.debug(e)
         end
       end
+
+      def partners_endpoint
+        return 'https://partners.shopify.com' if ENV[LOCAL_DEBUG].nil?
```
Comment (andyw8) [inline lib/project_types/node/commands/create.rb:118]: This is fairly minor, but I think it would be nice to flip these checks, e.g.

```
return 'https://partners.myshopify.io' if ENV[LOCAL_DEBUG]
'https://partners.shopify.com'
```

Often the early returns in a method are handle special cases, sometimes known as a [Guard clause](https://wiki.c2.com/?GuardClause).

**Review by andyw8 — APPROVED** [review]

**Comment by tanema** [comment]
I am starting to wonder if we should have variables accessible in the messages interpolation like $partners_url
