### PR TITLE
Fix bad config caching in tests

### LINKED ISSUE #914: Order-dependent test failures
We're seeing occasional failures such as https://travis-ci.com/github/Shopify/shopify-app-cli/jobs/399942541

I was able to reproduce this locally with:

```
TESTOPTS="--seed=7799" dev test
```

### PR DESCRIPTION
**Pull request by andyw8**
This appears to resolve a failure that we frequently see in the tests:

https://travis-ci.com/github/Shopify/shopify-app-cli/jobs/399942541

Fixes #914

### CODE REVIEW

**Review by paulomarg — APPROVED** [review]

File: lib/shopify-cli/project.rb [hunk 1]
```diff
@@ -95,6 +95,11 @@ def project_name
         File.basename(current.directory)
       end
 
+      def clear
```
Comment (paulomarg) [inline lib/shopify-cli/project.rb:98]: This is a useful method. We may want to enhance the `current` method to call `clear` if `force_reload` is set rather than passing it down as a parameter - that would keep our behaviour more consistent across the methods.
