### PR TITLE
Gracefully ignore ArgumentError in the shim check

### LINKED ISSUE #740: new shopify cli 1.0.0 installed but got error
# Issue summary
I've just migrated new version from old version according to https://shopify.github.io/shopify-app-cli/getting-started/migrate/
After installing, the directory "~/.shopify-app-cli/" doesn't generated and displayed error when I try any `shopify` command.

error:
```
Traceback (most recent call last):
        6: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:30:in `<main>'
        5: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        4: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        3: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:31:in `block in <main>'
        2: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `call'
        1: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `open'
/usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `initialize': The given fd is not accessible because RubyVM reserves it (ArgumentError)
```

## Expected behavior
generate /.shopify-app-cli/ and then I can use `shopify` command

## Actual behavior
not generate /.shopify-app-cli/ and error displayed

## Steps to reproduce the problem

1. uninstall the old one. `$ rm -rf ~/.shopify-app-cli/` and then commented out the line I found in `~/.zshrc` 
1. install new version. `$ brew tap shopify/shopify` then `$ brew install shopify-cli`
1. run `shopify version` to display error message

## Specifications

- App type: 1.0.0 
- Operating System: macOS Catalina 10.15.5
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

### PR DESCRIPTION
**Pull request by paulomarg**
### WHY are these changes introduced?

Fixes #740 and #742 

After the release of v1.0.0, we received some reports of the CLI failing to run under RVM because it throws an error when trying to load FD 9 (previously used by the shell shim). The RVM raises an ArgumentError in that case which prevents commands from going forward.

### WHAT is this pull request doing?

This PR adds a check for that particular error so that it cleanly skips this error. I've tested (using FD 3 since I couldn't reproduce this issue with 9) that if the FD exists before we go into Ruby we don't get the error - so we can say that if we got ArgumentError the FD did not exist before Ruby ran. See below:

```
$ irb
2.7.0 :001 > File.for_fd(3)
Traceback (most recent call last):
        5: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
        4: from /usr/share/rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
        3: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `for_fd'
ArgumentError (The given fd is not accessible because RubyVM reserves it)

$ tmpfile="$(\mktemp -u)"
$ exec 3>"${tmpfile}"
$ rm -f "${tmpfile}"
$ irb
2.7.0 :001 > File.for_fd(3)
 => #<File:fd 3>
```

### CODE REVIEW

File: lib/shopify-cli/core/entry_point.rb [hunk 1]
```diff
@@ -11,6 +11,8 @@ def call(args, ctx = Context.new)
             IO.open(9) { is_shell_shim = true }
           rescue Errno::EBADF
             # This is expected if the descriptor doesn't exist
+          rescue ArgumentError
```
Comment (andyw8) [inline lib/shopify-cli/core/entry_point.rb:14]: It's low risk, but we might want to check for a specific message here before suppressing it, just in case there could be some other thing that raises an `ArgumentError`.
