### PR TITLE
Started catching 'file not found' errors thrown when we check for nod…

### LINKED ISSUE #552: shopify create:  `spawn': No such file or directory - node (Errno::ENOENT)
On Windows (from Ubuntu WSL)

when running `shopify create`

am getting the following error:

```
Traceback (most recent call last):
        33: from /home/neil/.shopify-app-cli/bin/shopify:36:in `<main>'
        32: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        31: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        30: from /home/neil/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        29: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        28: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:25:in `log'
        27: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        26: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        25: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        24: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        23: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        22: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        21: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        20: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        19: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        18: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        17: from /home/neil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        16: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        15: from /home/neil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        14: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        13: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        12: from /home/neil/.shopify-app-cli/lib/shopify-cli/commands/create.rb:8:in `call'
        11: from /home/neil/.shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
        10: from /home/neil/.shopify-app-cli/lib/shopify-cli/commands/create.rb:25:in `call'
         9: from /home/neil/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
         8: from /home/neil/.shopify-app-cli/lib/project_types/node/commands/create.rb:26:in `call'
         7: from /home/neil/.shopify-app-cli/lib/project_types/node/commands/create.rb:72:in `check_node'
         6: from /home/neil/.shopify-app-cli/lib/shopify-cli/context.rb:268:in `capture2e'
         5: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:68:in `capture2e'
         4: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:176:in `delegate_open3'
         3: from /usr/lib/ruby/2.7.0/open3.rb:390:in `capture2e'
         2: from /usr/lib/ruby/2.7.0/open3.rb:208:in `popen2e'
         1: from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - node (Errno::ENOENT)
```

### PR DESCRIPTION
**Pull request by paulomarg**
Started catching 'file not found' errors thrown when we check for node / npme / npm and they are not installed

### WHY are these changes introduced?

The CLI was raising an error when checking for node / npm installations when they were not present.

Fixes #552  

### WHAT is this pull request doing?

Adding a rescue block specifically for the 'file not found' error thrown in this scenario. The previous behaviour of aborting the current command still applies, but we return a proper error message instead of an exception now.

### CODE REVIEW

File: lib/project_types/node/commands/create.rb [hunk 1]
```diff
@@ -67,12 +67,18 @@ def check_node
         version, stat = @ctx.capture2e('node', '-v')
         @ctx.done("node #{version}")
         @ctx.abort(NODE_REQUIRED_NOTICE) unless stat.success?
+      rescue Errno::ENOENT
```
Comment (tanema) [inline lib/project_types/node/commands/create.rb:70]: I think this is a good way to do it could mask other errors. What we could do instead so that we can make better error messages for the user is `@ctx.system('which', 'node').success?` This will allow us to specifically check if the tool exists.

Comment (andyw8) [reply lib/project_types/node/commands/create.rb:70]: I think that would fail in Windows, do we to support that?

Comment (paulomarg) [reply lib/project_types/node/commands/create.rb:70]: Yes, the original error was in Windows. I also thought of that @tanema, but we are actually printing out the version, and this enables us to do it with a single command. I do agree that 'which' would be the ideal choice but I'm not aware of a check that works across different OSs.

Comment (mkevinosullivan) [reply lib/project_types/node/commands/create.rb:70]: Our Windows support is currently through Windows Subsystem for Linux (WSL), so it's not native Windows but Linux.  So the `which` check would work.

Comment (paulomarg) [reply lib/project_types/node/commands/create.rb:70]: Excellent point! I think we should then go ahead and do as @tanema proposes.

File: lib/project_types/node/commands/create.rb [hunk 2]
```diff
@@ -64,15 +64,19 @@ def self.help
       private
 
       def check_node
-        version, stat = @ctx.capture2e('node', '-v')
-        @ctx.done("node #{version}")
+        output, stat = @ctx.capture2e('which', 'node')
         @ctx.abort(NODE_REQUIRED_NOTICE) unless stat.success?
+
+        version, = @ctx.capture2e('node', '-v')
```
Comment (andyw8) [inline lib/project_types/node/commands/create.rb:70]: Not critical, but if we wanted to be extra cautious we also also check `stat.success?` again here, in case the `node` installation was broken in some way.

Comment (paulomarg) [reply lib/project_types/node/commands/create.rb:70]: Don't see why not :), let's do that too.

File: test/project_types/node/commands/create_test.rb [hunk 3]
```diff
@@ -52,7 +69,9 @@ def test_check_default_npm_registry_is_production
         FileUtils.touch('test-app/server/handlers/client.js')
         FileUtils.touch('test-app/server/handlers/client.cli.js')
 
+        @context.expects(:capture2e).with('which', 'npm').returns(['/usr/bin/npm', mock(success?: true)])
```
Comment (andyw8) [inline test/project_types/node/commands/create_test.rb:72]: I wonder if it's worth extracting out some of the common stubbing since we're repeating it several times?

File: test/project_types/node/commands/create_test.rb [hunk 4]
```diff
@@ -30,20 +30,37 @@ def test_prints_help_with_no_name_argument
...
         Create.any_instance.stubs(:check_node)
-        @context.expects(:capture2e).with('npm', '-v').returns([nil, mock(success?: false)])
+        @context.expects(:capture2e).with('which', 'npm').returns([nil, mock(success?: false)])
         assert_raises ShopifyCli::Abort, Create::NPM_REQUIRED_NOTICE do
           perform_command
         end
       end
 
+      def test_check_get_npm_version
+        Create.any_instance.stubs(:check_node)
```
Comment (andyw8) [inline test/project_types/node/commands/create_test.rb:56]: I see we're already doing it above, and it's not critical, but in general I think we should try to avoid stubbing on the class being tested:

https://thoughtbot.com/blog/don-t-stub-the-system-under-test

Comment (paulomarg) [reply test/project_types/node/commands/create_test.rb:56]: This stubbing is quite easy to get rid of by adding mocks for the node check commands, so I agree that we can just drop it.
