### PR TITLE
Better tooling around opening urls

### LINKED ISSUE #337: Latest Release breaks existing build (ShopifyCli::OAuth::Error)
# Issue summary

Latest shopify-cli update breaks an existing project build

## Actual behavior

<details>*****@DESKTOP-******:/mnt/d/Checkouts/08631-amrita-nutrition-app$ shopify serve
/home/*****/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /mnt/c/ProgramData in PATH, mode 040777
✓ ngrok tunnel running at https://d8d170d6.ngrok.io
✓ ngrok tunnel running at https://d8d170d6.ngrok.io
open: ioctl(VT_GETSTATE): Inappropriate ioctl for device
This command ran with ID: 52941
Please include this information in any issues/report along with relevant logs
#<Thread:0x00007fffc237a518@/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:87 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:103:in `block in listen_local'
/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:102:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
        33: from /home/*****/.shopify-app-cli/bin/shopify:36:in `<main>'
        32: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        31: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        30: from /home/*****/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        29: from /home/*****/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
        28: from /home/*****/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
        27: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        26: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        25: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        24: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        23: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        22: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        21: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        20: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        19: from /home/*****/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        18: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        17: from /home/*****/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        16: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        15: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        14: from /home/*****/.shopify-app-cli/lib/shopify-cli/command.rb:22:in `call'
        13: from /home/*****/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:15:in `call'
        12: from /home/*****/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
        11: from /home/*****/.shopify-app-cli/lib/shopify-cli/tasks/update_whitelist_url.rb:9:in `call'
        10: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
         9: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
         8: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
         7: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
         6: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
         5: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
         4: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
         3: from /home/*****/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
         2: from /home/*****/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:14:in `call'
         1: from /home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:57:in `authenticate'
/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:111:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)</details>

## Specifications

- Operating System: Windows 10
- Shell: WSL Bash
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

### PR DESCRIPTION
**Pull request by tanema**
### WHY are these changes introduced?
Fixes #337

Currently opening urls is not cross platform compatible. 

### WHAT is this pull request doing?
This tries for best guess opening functionality and falls back to outputting the url to the console for the user to open the url for themselves.

### CODE REVIEW

File: lib/shopify-cli/helpers/os.rb [hunk 1]
```diff
@@ -1,6 +1,13 @@
 module ShopifyCli
   module Helpers
     module OS
+      OPEN_COMMANDS = {
+        'open' => 'open',
+        'xdg-open' => 'xdg-open',
+        'rundll32' => 'rundll32 url.dll,FileProtocolHandler',
```
Comment (tylerball) [inline lib/shopify-cli/helpers/os.rb]: image
